name: Create UI Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "e.g: v2.8.4"
        required: true
  push:
    tags:
      - 'v*'  # This will trigger on any tag starting with 'v'

jobs:
  mirror-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Get the version
      id: get_version
      env:
        #GITHUB_REF: ${{ github.ref }} ## use this one
        GITHUB_REF: refs/tags/{{ github.event.inputs.tag }}
      run: | 
        echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Create tag in target repository
      env:
        TARGET_REPO: "rafaelbreno/rancher-ui"
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git clone https://${GH_TOKEN}@github.com/${TARGET_REPO}.git target_repo
        cd target_repo
        git tag $VERSION
        git push origin $VERSION
        git push https://${GH_TOKEN}@github.com/${TARGET_REPO}.git $VERSION
